name: 'Deploy Terraform Infra in TEST environment'

on: 
  workflow_dispatch:
    inputs:
      workspace_folder: 
        description: 'Workspace Folder ej. "browserless-chrome-instances/aws"'
        required: true

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: test
    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
    
    - run: ls
    - run: echo | ls
